name: pnote
description: Simple app for notes


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.1
  sqflite: ^1.3.0
  path_provider: ^1.6.27
  provider: ^4.3.2+3
  path: ^1.7.0
  intl: ^0.16.1
  superellipse_shape: ^0.1.5
  focused_menu: ^1.0.2
  carousel_slider: ^2.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.14.4


flutter:

  uses-material-design: true

  assets:
    - assets/mood_icons/
